from ctypes import *

class VehicleData(Structure):
    _fields_ = [("vehicle_gear",c_ushort),\
                ("vehicle_gear_timestamp",c_ulonglong),\
                ("vehicle_steer_wheel_angle",c_float),\
                ("vehicle_steer_wheel_angle",c_float),\
                ("vehicle_steer_wheel_angle",c_float),\
                ("vehicle_steer_timestamp",c_ulonglong),\
                ("vehicle_wheel_angle",c_float),\
                ("vehicle_turn_left_signal",c_ushort),\
                ("vehicle_turn_right_signal",c_ushort),\
                ("vehicle_turn_signal_timestamp",c_ulonglong),\
                ("vehicle_high_beam",c_ushort),\
                ("vehicle_low_beam",c_ushort),\
                ("vehicle_beam_timestamp",c_ulonglong),\
                ("vehicle_engine_torque",c_float),\
                ("vehicle_engine_torque_timestamp",c_ulonglong),\
                ("vehicle_throttle_pedal",c_float),\
                ("vehicle_break_pedal",c_float),\
                ("vehicle_pedal_timestamp",c_longlong),\
                ("vehicle_front_left_wheel_speed",c_float),\
                ("vehicle_front_right_wheel_speed",c_float),\
                ("vehicle_rear_left_wheel_speed",c_float),\
                ("vehicle_rear_right_wheel_speed",c_float),\
                ("vehicle_front_left_wheel_speed_direction",c_ushort),\
                ("vehicle_front_right_wheel_speed_direction",c_ushort),\
                ("vehicle_rear_left_wheel_speed_direction",c_ushort),\
                ("vehicle_rear_right_wheel_speed_direction",c_ushort),\
                ("vehicle_front_left_wheel_pulse",c_ushort),\
                ("vehicle_front_right_wheel_pulse",c_ushort),\
                ("vehicle_rear_left_wheel_pulse",c_ushort),\
                ("vehicle_rear_right_wheel_pulse",c_ushort),\
                ("vehicle_speed",c_ushort),\
                ("vehicle_wheel_speed_timestamp",c_ulonglong),\
                ("vehicle_yaw_rate",c_float),\
                ("vehicle_acc_x",c_float),\
                ("vehicle_acc_y",c_float),\
                ("vehicle_yaw_timestamp",c_ulonglong),\
                ("vehicle_EPB_status",c_ushort),\
                ("vehicle_seat_belt_status",c_ushort),\
                ("vehicle_bonnet",c_ushort),\
                ("vehicle_DriverDoor",c_ushort),\
                ("vehicle_PsngrDoor",c_ushort),\
                ("vehicle_LHRDoor",c_ushort),\
                ("vehicle_RHRDoor",c_ushort),\
                ("vehicle_TrunkDoor",c_ushort),\
                ("vehicle_SunroofDoor",c_ushort),\
                ("vehicle_wing_mirror_left",c_ushort),\
                ("vehicle_wing_mirror_right",c_ushort),\
                ("vehicle_wiper",c_ushort),\
                ("vehicle_StandStill",c_ushort),\
                ("vehicle_brake_light",c_ushort),\
                ("vehicle_LFWindow",c_ushort),\
                ("vehicle_LRWindow",c_ushort),\
                ("vehicle_RFWindow",c_ushort),\
                ("vehicle_RRWindow",c_ushort),\
                ("Vehicle_DriverSeatAngle",c_ushort),\
                ("vehicle_status_timestamp",c_ulonglong),\
                ("CarBodyRollingCounter",c_ubyte)]
#print(sizeof(VehicleData))
